name: Node.js Package

on:
  push:
    tags:
      - "v*.*.*" # 匹配 v1.0.0 等标准版本号
      - "v*.*.*-*" # 匹配 v1.0.0-0、v1.0.4-beta 等预发布版本号

jobs:
  cache-and-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

  build:
    needs: cache-and-install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use cached Node.js and pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Build the package
        run: pnpm build # 使用之前的 pnpm 进行打包

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: pnpm install # 使用 pnpm 安装依赖
      - run: pnpm publish # 使用 pnpm 发布包
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
